-- 코드를 입력하세요
(SELECT DATE_FORMAT(O.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, O.PRODUCT_ID, O.USER_ID, O.SALES_AMOUNT
FROM ONLINE_SALE O
LEFT JOIN OFFLINE_SALE F ON O.PRODUCT_ID = F.PRODUCT_ID
WHERE YEAR(O.SALES_DATE) = 2022
AND MONTH(O.SALES_DATE) = 3

UNION

SELECT DATE_FORMAT(F.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, F.PRODUCT_ID, NULL AS USER_ID, F.SALES_AMOUNT
FROM OFFLINE_SALE F
RIGHT JOIN ONLINE_SALE O ON O.PRODUCT_ID = F.PRODUCT_ID
WHERE YEAR(F.SALES_DATE) = 2022
AND MONTH(F.SALES_DATE) = 3)
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC